name: mktrack
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - cython=0.29
  - matplotlib-base=3.5
  - ninja=1.10
  - ninja-base=1.10
  - pandas=1.4
  - pillow=9.4
  - pip=23.1
  - pycocotools=2.0
  - pymediainfo=6.1
  - python=3.8
  - seaborn=0.12
  - torchmetrics=0.10
  - pip:
    - attrs==21.4.0
    - entrypoints==0.3
    - iprogress==0.4
    - joblib==1.3.1
    - numpy==1.20.0
    - pytz==2021.3
    - pyyaml==6.0
    - scikit-learn==1.3.0
    - threadpoolctl==3.1.0
    - torch==1.7
    - torchvision==0.8
